Repository short-d/gitops, pull requests merged in 2020-03, with the labels that each got.

#35 Add certificate renewal script
  scripts/certs
Labels: size/S

#36 Add production config for status frontend service
  apps/status/frontend.production.yaml
Labels: size/M

#37 Upgrade ingress version to 0.30.0
  infrastructures/ingress.yaml
Labels: size/XS

#38 Add cert upgrade script for keel and kube-system
  infrastructures/keel.yaml
  scripts/certs
Labels: size/S

#39 Revert "Upgrade ingress version to 0.30.0"
  infrastructures/ingress.yaml
Labels: size/XS

#40 Add configs for testing environment
  apps/kgs/testing.yaml
  apps/short/backend.testing.yaml
  apps/short/frontend.testing.yaml
  apps/status/frontend.testing.yaml
  environments/testing-namespace.yaml
  scripts/certs
Labels: size/L

#41 Setup testing
  apps/kgs/testing.yaml
  apps/short/backend.testing.yaml
  apps/short/frontend.testing.yaml
Labels: size/L
