Repository short-d/gitops, pull requests merged in 2020-07, with the labels that each got.

#76 Add configuration for story
  apps/story/production.yaml
  apps/story/staging.yaml
  apps/story/testing.yaml
Labels: size/L

#77 Configure TLS encryption for Short gRPC API
  apps/short/backend.production.yaml
  apps/short/backend.staging.yaml
  apps/short/backend.testing.yaml
Labels: enhancement, size/M

#78 Change entrypoint to HTTPs
  apps/short/backend.production.yaml
  apps/short/backend.staging.yaml
  apps/short/backend.testing.yaml
Labels: size/XS
